// Compiles design-system/tokens.json into src/styles/tokens.css.
//
// Type styles are emitted with a `t-` prefix (.t-nav, .t-footer) because the
// unprefixed names collide with component class names in this repo.
// The JSON is the source of truth and is exported from the n0rdp0l design
// system artifact. Never hand-edit tokens.css; edit the JSON and re-run.
//
//   node scripts/build-tokens.mjs
//
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = resolve(root, 'design-system/tokens.json');
const OUT = resolve(root, 'src/styles/tokens.css');

const t = JSON.parse(readFileSync(SRC, 'utf8'));
const esc = (n) => n.replace(/\./g, '\\.');
const out = [];

out.push('/* GENERATED by scripts/build-tokens.mjs from design-system/tokens.json.');
out.push(` * Design system: ${t.name} v${t.version}. Do not edit by hand. */`);
out.push('');

const themes = t.color?.themes ?? [];
const first = themes[0]?.id;
const val = (v, theme) =>
  typeof v === 'string' ? v : v?.[theme] ?? v?.[first];
const ref = (v) =>
  typeof v === 'string' && /^\{.+\}$/.test(v) ? `var(--${v.slice(1, -1)})` : v;

for (const [i, theme] of themes.entries()) {
  const sel = i === 0
    ? `:root,\n[data-theme="${theme.id}"]`
    : `[data-theme="${theme.id}"]`;
  out.push(`${sel} {`);
  for (const tok of t.color?.tokens ?? []) {
    const v = val(tok.value, theme.id);
    if (v == null) continue;
    if (i > 0 && val(tok.value, first) === v) continue;
    out.push(`  --${esc(tok.name)}: ${ref(v)};`);
  }
  out.push('}');
  out.push('');
}

const plain = ['spacing', 'radius', 'border', 'measure', 'shadow', 'opacity', 'zIndex'];
out.push(':root {');
for (const fam of plain) {
  for (const tok of t[fam]?.tokens ?? []) {
    out.push(`  --${esc(tok.name)}: ${tok.value};`);
  }
}
for (const [key, stack] of Object.entries(t.type?.families ?? {})) {
  out.push(`  --font-${key}: ${stack};`);
}
out.push('}');
out.push('');

for (const group of t.type?.groups ?? []) {
  out.push(`/* ${group.name} */`);
  for (const s of group.styles ?? []) {
    const fam = s.family ?? group.family;
    const d = [];
    if (fam) d.push(`font-family: var(--font-${fam});`);
    if (s.fontSize != null) d.push(`font-size: ${typeof s.fontSize === 'number' ? s.fontSize + 'px' : s.fontSize};`);
    if (s.lineHeight != null) d.push(`line-height: ${s.lineHeight};`);
    if (s.fontWeight != null) d.push(`font-weight: ${s.fontWeight};`);
    if (s.letterSpacing != null) d.push(`letter-spacing: ${s.letterSpacing};`);
    if (s.fontStyle) d.push(`font-style: ${s.fontStyle};`);
    out.push(`.t-${esc(s.name)} { ${d.join(' ')} }`);
  }
  out.push('');
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join('\n'), 'utf8');
console.log(`tokens.css written: ${out.length} lines, ${t.color?.tokens?.length ?? 0} colours, ${themes.length} themes`);
